### ISSUE TITLE
Python 3.10

### ISSUE THREAD

**Issue by jvesely** [PrincetonUniversity/PsyNeuLink#2164]
This is a collection of issues that need to be fixed before PNL can run on Python 3.10:

- [x] numpy provides Python 3.10 wheels (https://pypi.org/project/numpy/1.21.2/#files)
- [x] scipy doesn't provide Python 3.10 wheels (will be available with 1.7.2 https://github.com/scipy/scipy/issues/14567)
- [x] llvmlite doesn't provide Python 3.10 wheels (will be available with 0.38.0 https://github.com/numba/llvmlite/issues/792)
- [x] pytorch doesn't provide Python 3.10 wheels (will be available with 1.11.0 https://github.com/pytorch/pytorch/issues/66424) 
- [x] 'collections' can no longer be imported directly, breaking typecheck-decorator (see #1703 ) https://github.com/jvesely/PsyNeuLink/runs/4049654543?check_suite_focus=true

**Comment by jvesely** [comment]
scipy 1.7.2 has been release with python 3.10 support

**Comment by jvesely** [comment]
llvmlite 0.38 released with Python 3.10 support

**Comment by jvesely** [comment]
pytorch 1.11 has been released with python 3.10 support

**Comment by jvesely** [comment]
running on python3.10 produces the following results:
= 2561 failed, 3486 passed, 3274 skipped, 1761 xfailed, 2179 warnings, 48 errors in 1559.37s (0:25:59) =
All of the errors 2544 failures have the same root cause:
`TypeError: Mechanism_Base.execute() got an unexpected keyword argument 'variable'`

the remaining errors are in documentation test; probably indirect version fo the above.
and llvm printf tests.
